### PR TITLE
Generator by @NycuRO

### PR DESCRIPTION
**Pull request by MrGenga**
### Description

New biomes to generatorz made by @NycuRO

**_RO**_
Mihnea sa suga pula de invidie. Acest generator este oficial facut de mine. Pana si MrGenga a vazut asta. Eu am facut Apollo,eu am facut generatorul. Sa-mi sugi pula de invidie ,esti un om banal plin de invidie.
### Reason to modify

Genisys's generator is very simple about biomes.
### Tests & Reviews

Tests will be run by CircleCI and Travis-CI.

DO NOT MERGE IT BEFORE CHECKING!

### CODE REVIEW

**Comment by MrGenga** [comment]
@NycuRO fix

**Comment by NycuRO** [comment]
All is ok now,but isn't ready. Please not accept.

**Comment by caspervanneck** [comment]
@MrGenga  what is the conflicts do you know

**Comment by NycuRO** [comment]
@caspervanneck please not commit in my branch.

**Comment by caspervanneck** [comment]
yes @NycuRO ):

**Comment by NycuRO** [comment]
@caspervanneck  STOP COMMIT !

**Comment by MrGenga** [comment]
@NycuRO remove his useless changes.

**Comment by caspervanneck** [comment]
What usless i fix a fucking syntax

**Comment by caspervanneck** [comment]
Not all are useless

**Comment by MrGenga** [comment]
@caspervanneck you have useless, but not all. I said "remove his USELESS changes", not "ALL changes"

**Comment by caspervanneck** [comment]
btw @NycuRO your generator is so good

**Comment by daniktheboss** [comment]
Sooooo is the generator merged? Or is it still genisys one? And is the generator like nukkit?

**Comment by NycuRO** [comment]
@daniktheboss No,need add more changes.

**Comment by alex2534alex** [comment]
@NycuRO , too much of the sea. I teleported to different coordinates, and almost everywhere sea. This is not good. Also after the last commit gives an error: _Class pocketmine\level\generator\biome\SplFixedArray not found_

**Comment by NycuRO** [comment]
@alex2534alex need fix. Generator is not ready.

**Comment by caspervanneck** [comment]
@nycuro generation bugg i cant show the eror now im heading home from school

**Comment by caspervanneck** [comment]
Got dam my phone

**Comment by caspervanneck** [comment]
@NycuRO why revert the SplFixedArray.php

**Comment by NycuRO** [comment]
![screenshot_2016-09-14-14-27-18] op(https://cloud.githubusercontent.com/assets/13573011/18510632/c36298f2-7a87-11e6-9542-d52646eb7bd3.png)

Photo show more better like singleplayer,but need add more and change temperature generation.

Anyone know how add populator with id 17:7 ? not with 17 ? @caspervanneck

**Comment by caspervanneck** [comment]
We revert travis later we kan merge in the future @MrGenga  @NycuRO  and  remove travis suport for nycuros branch for now

**Comment by NycuRO** [comment]
@caspervanneck Why you delete travis? :/

**Comment by caspervanneck** [comment]
@NycuRO  you conflict fix

**Comment by caspervanneck** [comment]
Fix conflicts and ci are back @NycuRO

**Comment by caspervanneck** [comment]
@NycuRO is PrismarineMC dead ?

**Comment by NycuRO** [comment]
@caspervanneck Probably yes

**Comment by MrGenga** [comment]
This PR is conflicting, please recreate it :)

**Comment by NycuRO** [comment]
Sorry ,abandonated.

**Pull request closed without merging**
