### PR TITLE
Desktop UI inventory support

### PR DESCRIPTION
**Pull request by Encritary**
Desktop UI inventory support, came from Genisys and made mostly by @dktapps. 
**Needs a lot of testing before merge with master.**

### CODE REVIEW

**Comment by dktapps** [comment]
🤦‍♂️

**Comment by Encritary** [comment]
@dktapps But it works, lol.

**Comment by dktapps** [comment]
🤦‍♂️

**Comment by RedstoneAlmeida** [comment]
@Encritary he hate genisyspro

**Comment by Encritary** [comment]
@RedstoneAlmeida it's from original PR from Genisys.

**Comment by RedstoneAlmeida** [comment]
@Encritary getSourceItem() in Transaction is necessary

**Comment by Encritary** [comment]
@RedstoneAlmeida Join up in our discord: https://discord.gg/mR7MRKa Let's discuss it there.

**Comment by RedstoneAlmeida** [comment]
@Encritary I'm there

**Comment by Encritary** [comment]
It was tested a lot of times. Everything is working, merging with master.

**Pull request merged**
